# Generated by Django 4.2.5 on 2023-09-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkgif', '0005_animation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='animation',
            name='rendered_animation',
            field=models.CharField(max_length=100, default='', blank=True),
            preserve_default=False,
        ),
    ]
