# Generated by Django 4.2.5 on 2023-09-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkgif', '0007_alter_animation_rendered_animation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='rendered_animation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
