# Generated by Django 4.2.5 on 2023-09-22 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mkgif', '0008_alter_animation_rendered_animation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animation',
            name='rendered_animation',
        ),
    ]
